/*
 * Hand-crafted dxxsconf.h for Android builds of D1X-Rebirth.
 * Normally generated by SCons configure step.
 */

#pragma once

/* Build Descent 1 */
#define DXX_BUILD_DESCENT 1

/* OpenGL ES rendering */
#define DXX_USE_OGL 1
#define DXX_USE_OGLES 1

/* SDL2_mixer for audio */
#define DXX_USE_SDLMIXER 1

/* No SDL_image */
#define DXX_USE_SDLIMAGE 0

/* No level editor */
#define DXX_USE_EDITOR 0

/* No share path (data is bundled or in app-specific storage) */
#define DXX_USE_SHAREPATH 0

/* Networking support */
#define DXX_USE_MULTIPLAYER 1
#define DXX_USE_UDP 1
#define DXX_USE_IPv6 0
#define DXX_USE_TRACKER 0

/* No ADLMIDI */
#define DXX_USE_ADLMIDI 0

/* No stereoscopic rendering */
#define DXX_USE_STEREOSCOPIC_RENDER 0

/* Screenshot support (legacy format) */
#define DXX_USE_SCREENSHOT 1
#define DXX_USE_SCREENSHOT_FORMAT_PNG 0
#define DXX_USE_SCREENSHOT_FORMAT_LEGACY 1

/* No SDL1 redbook audio */
#define DXX_USE_SDL_REDBOOK_AUDIO 0

/* No debug memory allocator */
/* DXX_USE_DEBUG_MEMORY_ALLOCATOR not defined */

/* x86_64 is little-endian */
#define DXX_WORDS_BIGENDIAN 0

/* No word alignment fixups needed on x86_64 */
#define DXX_WORDS_NEED_ALIGNMENT 0

/* Joystick support */
#define DXX_MAX_JOYSTICKS 8
#define DXX_MAX_AXES_PER_JOYSTICK 128
#define DXX_MAX_BUTTONS_PER_JOYSTICK 128
#define DXX_MAX_HATS_PER_JOYSTICK 4

/* Version */
#define DXX_VERSION_SEQ 0,61,0

/* Android Bionic libc doesn't define ushort/uint in sys/types.h */
#ifdef __ANDROID__
#ifndef DXX_SCONF_NO_INCLUDES
typedef unsigned short ushort;
typedef unsigned int uint;
#endif
#endif

/* Compound statements (GCC extension, supported by Clang) */
#define DXX_BEGIN_COMPOUND_STATEMENT
#define DXX_END_COMPOUND_STATEMENT

/* Branch prediction hints */
#define likely(A) __builtin_expect(!!(A), 1)
#define unlikely(A) __builtin_expect(!!(A), 0)

/* Compiler feature detection - Clang 17 (NDK r26) supports all of these */

/* Function attributes */
#define dxx_compiler_attribute_always_inline() [[gnu::always_inline]]
#define dxx_compiler_attribute_alloc_size(A,...) __attribute__((alloc_size(A, ## __VA_ARGS__)))
#define dxx_compiler_attribute_cold [[gnu::cold]]
#define dxx_compiler_attribute_format_arg(A) __attribute__((format_arg(A)))
#define dxx_compiler_attribute_format_printf(A,B) __attribute__((format(printf,A,B)))
#define dxx_compiler_attribute_malloc() __attribute__((malloc))
#define dxx_compiler_attribute_nonnull(...) __attribute__((nonnull __VA_ARGS__))
#define dxx_compiler_attribute_used __attribute__((used))
#define dxx_compiler_attribute_unused __attribute__((unused))

#define DXX_HAVE_ATTRIBUTE_ERROR
#define dxx_compiler_attribute_error(M) __attribute__((error(M)))

#define DXX_HAVE_ATTRIBUTE_WARNING
#define dxx_compiler_attribute_warning(M) __attribute__((warning(M)))

#define DXX_HAVE_BUILTIN_BSWAP

#define DXX_HAVE_BUILTIN_CONSTANT_P
#define DXX_CONSTANT_TRUE(E) (__builtin_constant_p((E)) && (E))
#define dxx_builtin_constant_p(A) __builtin_constant_p(A)

#define DXX_HAVE_CXX_BUILTIN_FILE_LINE 1

#define DXX_HAVE_BUILTIN_OBJECT_SIZE 1

/* std::size_t format: "zu" on Linux/Android */
#define DXX_PRI_size_type "zu"

/* ptrdiff_t can be cast to int */
#define DXX_ptrdiff_cast_int static_cast<int>

/* size_t can be cast to unsigned */
#define DXX_size_t_cast_unsigned_int static_cast<unsigned>

/* strcasecmp is available */
#define DXX_HAVE_STRCASECMP

/* struct timespec is available */
#define DXX_HAVE_STRUCT_TIMESPEC

/* inet_ntop is available */
#define DXX_HAVE_INET_NTOP

/* Namespace disambiguation (Clang does not support this) */
/* DXX_HAVE_CXX_DISAMBIGUATE_USING_NAMESPACE not defined */

/* No Valgrind poison - must be defined to 0 (used in if constexpr) */
#define DXX_HAVE_POISON 0
#define DXX_HAVE_POISON_VALGRIND 0
#define DXX_HAVE_POISON_OVERWRITE 0

#ifndef DXX_SCONF_NO_INCLUDES
dxx_compiler_attribute_error("must never be called")
void DXX_ALWAYS_ERROR_FUNCTION(const char *);
#endif
