/* This is a generated file.  Do not edit.
 * This file was generated by /build/dxx-rebirth/similar/main/generate-kconfig-udlr.py
 * This file was generated from /tmp/kconfig.ui-table.i
 */

#include "dsx-ns.h"

namespace dsx {

/* kc_keyboard - udlr define */
#define D1X_KCONFIG_UI_UDLR_LINE_54()	/* [ 0] */	43,  2, 49,  1
#define D1X_KCONFIG_UI_UDLR_LINE_55()	/* [ 1] */	48,  3,  0, 24
#define D1X_KCONFIG_UI_UDLR_LINE_56()	/* [ 2] */	 0,  4, 25,  3
#define D1X_KCONFIG_UI_UDLR_LINE_57()	/* [ 3] */	 1,  5,  2, 26
#define D1X_KCONFIG_UI_UDLR_LINE_58()	/* [ 4] */	 2,  6, 27,  5
#define D1X_KCONFIG_UI_UDLR_LINE_59()	/* [ 5] */	 3,  7,  4, 28
#define D1X_KCONFIG_UI_UDLR_LINE_60()	/* [ 6] */	 4,  8, 29,  7
#define D1X_KCONFIG_UI_UDLR_LINE_61()	/* [ 7] */	 5,  9,  6, 34
#define D1X_KCONFIG_UI_UDLR_LINE_62()	/* [ 8] */	 6, 10, 35,  9
#define D1X_KCONFIG_UI_UDLR_LINE_63()	/* [ 9] */	 7, 11,  8, 36
#define D1X_KCONFIG_UI_UDLR_LINE_64()	/* [10] */	 8, 12, 37, 11
#define D1X_KCONFIG_UI_UDLR_LINE_65()	/* [11] */	 9, 13, 10, 44
#define D1X_KCONFIG_UI_UDLR_LINE_66()	/* [12] */	10, 14, 45, 13
#define D1X_KCONFIG_UI_UDLR_LINE_67()	/* [13] */	11, 15, 12, 30
#define D1X_KCONFIG_UI_UDLR_LINE_68()	/* [14] */	12, 16, 31, 15
#define D1X_KCONFIG_UI_UDLR_LINE_69()	/* [15] */	13, 17, 14, 32
#define D1X_KCONFIG_UI_UDLR_LINE_70()	/* [16] */	14, 18, 33, 17
#define D1X_KCONFIG_UI_UDLR_LINE_71()	/* [17] */	15, 19, 16, 38
#define D1X_KCONFIG_UI_UDLR_LINE_72()	/* [18] */	16, 20, 39, 19
#define D1X_KCONFIG_UI_UDLR_LINE_73()	/* [19] */	17, 21, 18, 40
#define D1X_KCONFIG_UI_UDLR_LINE_74()	/* [20] */	18, 22, 41, 21
#define D1X_KCONFIG_UI_UDLR_LINE_75()	/* [21] */	19, 23, 20, 42
#define D1X_KCONFIG_UI_UDLR_LINE_76()	/* [22] */	20, 46, 43, 23
#define D1X_KCONFIG_UI_UDLR_LINE_77()	/* [23] */	21, 47, 22, 46
#define D1X_KCONFIG_UI_UDLR_LINE_78()	/* [24] */	49, 26,  1, 25
#define D1X_KCONFIG_UI_UDLR_LINE_79()	/* [25] */	42, 27, 24,  2
#define D1X_KCONFIG_UI_UDLR_LINE_80()	/* [26] */	24, 28,  3, 27
#define D1X_KCONFIG_UI_UDLR_LINE_81()	/* [27] */	25, 29, 26,  4
#define D1X_KCONFIG_UI_UDLR_LINE_82()	/* [28] */	26, 34,  5, 29
#define D1X_KCONFIG_UI_UDLR_LINE_83()	/* [29] */	27, 35, 28,  6
#define D1X_KCONFIG_UI_UDLR_LINE_84()	/* [30] */	44, 32, 13, 31
#define D1X_KCONFIG_UI_UDLR_LINE_85()	/* [31] */	45, 33, 30, 14
#define D1X_KCONFIG_UI_UDLR_LINE_86()	/* [32] */	30, 38, 15, 33
#define D1X_KCONFIG_UI_UDLR_LINE_87()	/* [33] */	31, 39, 32, 16
#define D1X_KCONFIG_UI_UDLR_LINE_88()	/* [34] */	28, 36,  7, 35
#define D1X_KCONFIG_UI_UDLR_LINE_89()	/* [35] */	29, 37, 34,  8
#define D1X_KCONFIG_UI_UDLR_LINE_90()	/* [36] */	34, 44,  9, 37
#define D1X_KCONFIG_UI_UDLR_LINE_91()	/* [37] */	35, 45, 36, 10
#define D1X_KCONFIG_UI_UDLR_LINE_93()	/* [38] */	32, 40, 17, 39
#define D1X_KCONFIG_UI_UDLR_LINE_94()	/* [39] */	33, 41, 38, 18
#define D1X_KCONFIG_UI_UDLR_LINE_95()	/* [40] */	38, 42, 19, 41
#define D1X_KCONFIG_UI_UDLR_LINE_96()	/* [41] */	39, 43, 40, 20
#define D1X_KCONFIG_UI_UDLR_LINE_97()	/* [42] */	40, 25, 21, 43
#define D1X_KCONFIG_UI_UDLR_LINE_98()	/* [43] */	41,  0, 42, 22
#define D1X_KCONFIG_UI_UDLR_LINE_107()	/* [44] */	36, 30, 11, 45
#define D1X_KCONFIG_UI_UDLR_LINE_108()	/* [45] */	37, 31, 44, 12
#define D1X_KCONFIG_UI_UDLR_LINE_113()	/* [46] */	22, 48, 23, 47
#define D1X_KCONFIG_UI_UDLR_LINE_114()	/* [47] */	23, 49, 46, 48
#define D1X_KCONFIG_UI_UDLR_LINE_115()	/* [48] */	46,  1, 47, 49
#define D1X_KCONFIG_UI_UDLR_LINE_116()	/* [49] */	47, 24, 48,  0

/* kc_keyboard - enum blank */

#define DXX_KCONFIG_UI_LABEL_kc_keyboard	\
	/* [ 0] */	"Pitch forward" "\0"	\
	/* [ 2] */	"Pitch backward" "\0"	\
	/* [ 4] */	"Turn left" "\0"	\
	/* [ 6] */	"Turn right" "\0"	\
	/* [ 8] */	"Slide on" "\0"	\
	/* [10] */	"Slide left" "\0"	\
	/* [12] */	"Slide right" "\0"	\
	/* [14] */	"Slide up" "\0"	\
	/* [16] */	"Slide down" "\0"	\
	/* [18] */	"Bank on" "\0"	\
	/* [20] */	"Bank left" "\0"	\
	/* [22] */	"Bank right" "\0"	\
	/* [24] */	"Fire primary" "\0"	\
	/* [26] */	"Fire secondary" "\0"	\
	/* [28] */	"Fire flare" "\0"	\
	/* [30] */	"Accelerate" "\0"	\
	/* [32] */	"Reverse" "\0"	\
	/* [34] */	"Drop Bomb" "\0"	\
	/* [36] */	"REAR VIEW" "\0"	\
	/* [38] */	"Cruise Faster" "\0"	\
	/* [40] */	"Cruise Slower" "\0"	\
	/* [42] */	"Cruise Off" "\0"	\
	/* [44] */	"Automap" "\0"	\
	/* [46] */	"Cycle Primary" "\0"	\
	/* [48] */	"Cycle Second." "\0"

/* kc_joystick - udlr define */
#define D1X_KCONFIG_UI_UDLR_LINE_160()	/* [ 0] */	15,  1, 24, 29
#define D1X_KCONFIG_UI_UDLR_LINE_161()	/* [ 1] */	 0,  4, 34, 30
#define D1X_KCONFIG_UI_UDLR_LINE_162()	/* [ 2] */	26,  3, 37, 31
#define D1X_KCONFIG_UI_UDLR_LINE_163()	/* [ 3] */	 2, 25, 38, 32
#define D1X_KCONFIG_UI_UDLR_LINE_164()	/* [ 4] */	 1, 26, 35, 33
#define D1X_KCONFIG_UI_UDLR_LINE_165()	/* [ 5] */	23,  6, 29, 34
#define D1X_KCONFIG_UI_UDLR_LINE_166()	/* [ 6] */	 5,  7, 30, 35
#define D1X_KCONFIG_UI_UDLR_LINE_167()	/* [ 7] */	 6,  8, 33, 36
#define D1X_KCONFIG_UI_UDLR_LINE_168()	/* [ 8] */	 7,  9, 43, 37
#define D1X_KCONFIG_UI_UDLR_LINE_169()	/* [ 9] */	 8, 10, 31, 38
#define D1X_KCONFIG_UI_UDLR_LINE_170()	/* [10] */	 9, 11, 32, 39
#define D1X_KCONFIG_UI_UDLR_LINE_171()	/* [11] */	10, 12, 42, 40
#define D1X_KCONFIG_UI_UDLR_LINE_172()	/* [12] */	11, 44, 28, 41
#define D1X_KCONFIG_UI_UDLR_LINE_175()	/* [13] */	47, 15, 47, 14
#define D1X_KCONFIG_UI_UDLR_LINE_176()	/* [14] */	48, 16, 13, 17
#define D1X_KCONFIG_UI_UDLR_LINE_177()	/* [15] */	13,  0, 18, 16
#define D1X_KCONFIG_UI_UDLR_LINE_178()	/* [16] */	14, 29, 15, 19
#define D1X_KCONFIG_UI_UDLR_LINE_179()	/* [17] */	49, 19, 14, 18
#define D1X_KCONFIG_UI_UDLR_LINE_180()	/* [18] */	45, 20, 17, 15
#define D1X_KCONFIG_UI_UDLR_LINE_181()	/* [19] */	17, 21, 16, 20
#define D1X_KCONFIG_UI_UDLR_LINE_182()	/* [20] */	18, 22, 19, 21
#define D1X_KCONFIG_UI_UDLR_LINE_183()	/* [21] */	19, 23, 20, 22
#define D1X_KCONFIG_UI_UDLR_LINE_184()	/* [22] */	20, 24, 21, 23
#define D1X_KCONFIG_UI_UDLR_LINE_185()	/* [23] */	21,  5, 22, 24
#define D1X_KCONFIG_UI_UDLR_LINE_186()	/* [24] */	22, 34, 23,  0
#define D1X_KCONFIG_UI_UDLR_LINE_189()	/* [25] */	 3, 27, 39, 42
#define D1X_KCONFIG_UI_UDLR_LINE_190()	/* [26] */	 4,  2, 36, 43
#define D1X_KCONFIG_UI_UDLR_LINE_192()	/* [27] */	25, 48, 40, 28
#define D1X_KCONFIG_UI_UDLR_LINE_193()	/* [28] */	42, 49, 27, 12
#define D1X_KCONFIG_UI_UDLR_LINE_200()	/* [29] */	16, 30,  0,  5
#define D1X_KCONFIG_UI_UDLR_LINE_201()	/* [30] */	29, 33,  1,  6
#define D1X_KCONFIG_UI_UDLR_LINE_202()	/* [31] */	43, 32,  2,  9
#define D1X_KCONFIG_UI_UDLR_LINE_203()	/* [32] */	31, 42,  3, 10
#define D1X_KCONFIG_UI_UDLR_LINE_204()	/* [33] */	30, 43,  4,  7
#define D1X_KCONFIG_UI_UDLR_LINE_205()	/* [34] */	24, 35,  5,  1
#define D1X_KCONFIG_UI_UDLR_LINE_206()	/* [35] */	34, 36,  6,  4
#define D1X_KCONFIG_UI_UDLR_LINE_207()	/* [36] */	35, 37,  7, 26
#define D1X_KCONFIG_UI_UDLR_LINE_208()	/* [37] */	36, 38,  8,  2
#define D1X_KCONFIG_UI_UDLR_LINE_209()	/* [38] */	37, 39,  9,  3
#define D1X_KCONFIG_UI_UDLR_LINE_210()	/* [39] */	38, 40, 10, 25
#define D1X_KCONFIG_UI_UDLR_LINE_211()	/* [40] */	39, 41, 11, 27
#define D1X_KCONFIG_UI_UDLR_LINE_212()	/* [41] */	40, 46, 12, 48
#define D1X_KCONFIG_UI_UDLR_LINE_213()	/* [42] */	32, 28, 25, 11
#define D1X_KCONFIG_UI_UDLR_LINE_214()	/* [43] */	33, 31, 26,  8
#define D1X_KCONFIG_UI_UDLR_LINE_216()	/* [44] */	12, 45, 49, 46
#define D1X_KCONFIG_UI_UDLR_LINE_217()	/* [45] */	44, 18, 46, 47
#define D1X_KCONFIG_UI_UDLR_LINE_221()	/* [46] */	41, 47, 44, 45
#define D1X_KCONFIG_UI_UDLR_LINE_222()	/* [47] */	46, 13, 45, 13
#define D1X_KCONFIG_UI_UDLR_LINE_233()	/* [48] */	27, 14, 41, 49
#define D1X_KCONFIG_UI_UDLR_LINE_234()	/* [49] */	28, 17, 48, 44

/* kc_joystick - enum define */
enum class dxx_kconfig_ui_kc_joystick : unsigned {
#define dxx_kconfig_ui_kc_joystick_pitch_ud dxx_kconfig_ui_kc_joystick::pitch_ud
	pitch_ud = 13,
#define dxx_kconfig_ui_kc_joystick_invert_pitch dxx_kconfig_ui_kc_joystick::invert_pitch
	invert_pitch = 14,
#define dxx_kconfig_ui_kc_joystick_turn dxx_kconfig_ui_kc_joystick::turn
	turn = 15,
#define dxx_kconfig_ui_kc_joystick_invert_turn dxx_kconfig_ui_kc_joystick::invert_turn
	invert_turn = 16,
#define dxx_kconfig_ui_kc_joystick_slide_lr dxx_kconfig_ui_kc_joystick::slide_lr
	slide_lr = 17,
#define dxx_kconfig_ui_kc_joystick_invert_slide_lr dxx_kconfig_ui_kc_joystick::invert_slide_lr
	invert_slide_lr = 18,
#define dxx_kconfig_ui_kc_joystick_slide_ud dxx_kconfig_ui_kc_joystick::slide_ud
	slide_ud = 19,
#define dxx_kconfig_ui_kc_joystick_invert_slide_ud dxx_kconfig_ui_kc_joystick::invert_slide_ud
	invert_slide_ud = 20,
#define dxx_kconfig_ui_kc_joystick_bank dxx_kconfig_ui_kc_joystick::bank
	bank = 21,
#define dxx_kconfig_ui_kc_joystick_invert_bank dxx_kconfig_ui_kc_joystick::invert_bank
	invert_bank = 22,
#define dxx_kconfig_ui_kc_joystick_throttle dxx_kconfig_ui_kc_joystick::throttle
	throttle = 23,
#define dxx_kconfig_ui_kc_joystick_invert_throttle dxx_kconfig_ui_kc_joystick::invert_throttle
	invert_throttle = 24,
};

#define DXX_KCONFIG_UI_LABEL_kc_joystick	\
	/* [ 0] */	"Fire primary" "\0"	\
	/* [ 1] */	"Fire secondary" "\0"	\
	/* [ 2] */	"Accelerate" "\0"	\
	/* [ 3] */	"Reverse" "\0"	\
	/* [ 4] */	"Fire flare" "\0"	\
	/* [ 5] */	"Slide on" "\0"	\
	/* [ 6] */	"Slide left" "\0"	\
	/* [ 7] */	"Slide right" "\0"	\
	/* [ 8] */	"Slide up" "\0"	\
	/* [ 9] */	"Slide down" "\0"	\
	/* [10] */	"Bank on" "\0"	\
	/* [11] */	"Bank left" "\0"	\
	/* [12] */	"Bank right" "\0"	\
	/* [13] */	"Pitch U/D" "\0"	\
	/* [15] */	"Turn L/R" "\0"	\
	/* [17] */	"Slide L/R" "\0"	\
	/* [19] */	"Slide U/D" "\0"	\
	/* [21] */	"Bank L/R" "\0"	\
	/* [23] */	"Throttle" "\0"	\
	/* [25] */	"Rear view" "\0"	\
	/* [26] */	"Drop bomb" "\0"	\
	/* [27] */	"Automap" "\0"	\
	/* [29] */	"Fire primary" "\0"	\
	/* [30] */	"Fire secondary" "\0"	\
	/* [31] */	"Accelerate" "\0"	\
	/* [32] */	"Reverse" "\0"	\
	/* [33] */	"Fire flare" "\0"	\
	/* [34] */	"Slide on" "\0"	\
	/* [35] */	"Slide left" "\0"	\
	/* [36] */	"Slide right" "\0"	\
	/* [37] */	"Slide up" "\0"	\
	/* [38] */	"Slide down" "\0"	\
	/* [39] */	"Bank on" "\0"	\
	/* [40] */	"Bank left" "\0"	\
	/* [41] */	"Bank right" "\0"	\
	/* [42] */	"Rear view" "\0"	\
	/* [43] */	"Drop bomb" "\0"	\
	/* [44] */	"Cycle Primary" "\0"	\
	/* [45] */	"Cycle Secondary" "\0"	\
	/* [46] */	"" "\0"	\
	/* [47] */	"" "\0"	\
	/* [48] */	"Menu" "\0"

/* kc_mouse - udlr define */
#define D1X_KCONFIG_UI_UDLR_LINE_273()	/* [ 0] */	19,  1, 20,  5
#define D1X_KCONFIG_UI_UDLR_LINE_274()	/* [ 1] */	 0,  4,  5,  6
#define D1X_KCONFIG_UI_UDLR_LINE_275()	/* [ 2] */	26,  3,  8,  9
#define D1X_KCONFIG_UI_UDLR_LINE_276()	/* [ 3] */	 2, 25,  9, 10
#define D1X_KCONFIG_UI_UDLR_LINE_277()	/* [ 4] */	 1, 26,  6,  7
#define D1X_KCONFIG_UI_UDLR_LINE_278()	/* [ 5] */	23,  6,  0,  1
#define D1X_KCONFIG_UI_UDLR_LINE_279()	/* [ 6] */	 5,  7,  1,  4
#define D1X_KCONFIG_UI_UDLR_LINE_280()	/* [ 7] */	 6,  8,  4, 26
#define D1X_KCONFIG_UI_UDLR_LINE_281()	/* [ 8] */	 7,  9, 26,  2
#define D1X_KCONFIG_UI_UDLR_LINE_282()	/* [ 9] */	 8, 10,  2,  3
#define D1X_KCONFIG_UI_UDLR_LINE_283()	/* [10] */	 9, 11,  3, 25
#define D1X_KCONFIG_UI_UDLR_LINE_284()	/* [11] */	10, 12, 25, 27
#define D1X_KCONFIG_UI_UDLR_LINE_285()	/* [12] */	11, 22, 27, 28
#define D1X_KCONFIG_UI_UDLR_LINE_286()	/* [13] */	24, 15, 28, 14
#define D1X_KCONFIG_UI_UDLR_LINE_287()	/* [14] */	28, 16, 13, 21
#define D1X_KCONFIG_UI_UDLR_LINE_288()	/* [15] */	13, 17, 22, 16
#define D1X_KCONFIG_UI_UDLR_LINE_289()	/* [16] */	14, 18, 15, 23
#define D1X_KCONFIG_UI_UDLR_LINE_290()	/* [17] */	15, 19, 24, 18
#define D1X_KCONFIG_UI_UDLR_LINE_291()	/* [18] */	16, 20, 17, 19
#define D1X_KCONFIG_UI_UDLR_LINE_292()	/* [19] */	17,  0, 18, 20
#define D1X_KCONFIG_UI_UDLR_LINE_293()	/* [20] */	18, 21, 19,  0
#define D1X_KCONFIG_UI_UDLR_LINE_294()	/* [21] */	20, 23, 14, 22
#define D1X_KCONFIG_UI_UDLR_LINE_295()	/* [22] */	12, 24, 21, 15
#define D1X_KCONFIG_UI_UDLR_LINE_296()	/* [23] */	21,  5, 16, 24
#define D1X_KCONFIG_UI_UDLR_LINE_297()	/* [24] */	22, 13, 23, 17
#define D1X_KCONFIG_UI_UDLR_LINE_298()	/* [25] */	 3, 27, 10, 11
#define D1X_KCONFIG_UI_UDLR_LINE_299()	/* [26] */	 4,  2,  7,  8
#define D1X_KCONFIG_UI_UDLR_LINE_301()	/* [27] */	25, 28, 11, 12
#define D1X_KCONFIG_UI_UDLR_LINE_302()	/* [28] */	27, 14, 12, 13

/* kc_mouse - enum define */
enum class dxx_kconfig_ui_kc_mouse : unsigned {
#define dxx_kconfig_ui_kc_mouse_pitch_ud dxx_kconfig_ui_kc_mouse::pitch_ud
	pitch_ud = 13,
#define dxx_kconfig_ui_kc_mouse_invert_pitch dxx_kconfig_ui_kc_mouse::invert_pitch
	invert_pitch = 14,
#define dxx_kconfig_ui_kc_mouse_turn dxx_kconfig_ui_kc_mouse::turn
	turn = 15,
#define dxx_kconfig_ui_kc_mouse_invert_turn dxx_kconfig_ui_kc_mouse::invert_turn
	invert_turn = 16,
#define dxx_kconfig_ui_kc_mouse_slide_lr dxx_kconfig_ui_kc_mouse::slide_lr
	slide_lr = 17,
#define dxx_kconfig_ui_kc_mouse_invert_slide_lr dxx_kconfig_ui_kc_mouse::invert_slide_lr
	invert_slide_lr = 18,
#define dxx_kconfig_ui_kc_mouse_slide_ud dxx_kconfig_ui_kc_mouse::slide_ud
	slide_ud = 19,
#define dxx_kconfig_ui_kc_mouse_invert_slide_ud dxx_kconfig_ui_kc_mouse::invert_slide_ud
	invert_slide_ud = 20,
#define dxx_kconfig_ui_kc_mouse_bank dxx_kconfig_ui_kc_mouse::bank
	bank = 21,
#define dxx_kconfig_ui_kc_mouse_invert_bank dxx_kconfig_ui_kc_mouse::invert_bank
	invert_bank = 22,
#define dxx_kconfig_ui_kc_mouse_throttle dxx_kconfig_ui_kc_mouse::throttle
	throttle = 23,
#define dxx_kconfig_ui_kc_mouse_invert_throttle dxx_kconfig_ui_kc_mouse::invert_throttle
	invert_throttle = 24,
};

#define DXX_KCONFIG_UI_LABEL_kc_mouse	\
	/* [ 0] */	"Fire primary" "\0"	\
	/* [ 1] */	"Fire secondary" "\0"	\
	/* [ 2] */	"Accelerate" "\0"	\
	/* [ 3] */	"reverse" "\0"	\
	/* [ 4] */	"Fire flare" "\0"	\
	/* [ 5] */	"Slide on" "\0"	\
	/* [ 6] */	"Slide left" "\0"	\
	/* [ 7] */	"Slide right" "\0"	\
	/* [ 8] */	"Slide up" "\0"	\
	/* [ 9] */	"Slide down" "\0"	\
	/* [10] */	"Bank on" "\0"	\
	/* [11] */	"Bank left" "\0"	\
	/* [12] */	"Bank right" "\0"	\
	/* [13] */	"Pitch U/D" "\0"	\
	/* [15] */	"Turn L/R" "\0"	\
	/* [17] */	"Slide L/R" "\0"	\
	/* [19] */	"Slide U/D" "\0"	\
	/* [21] */	"Bank L/R" "\0"	\
	/* [23] */	"Throttle" "\0"	\
	/* [25] */	"REAR VIEW" "\0"	\
	/* [26] */	"Drop Bomb" "\0"	\
	/* [27] */	"Cycle Primary" "\0"	\
	/* [28] */	"Cycle Secondary" "\0"

/* kc_rebirth - udlr define */
#define D1X_KCONFIG_UI_UDLR_LINE_319()	/* [ 0] */	29,  3, 29,  1
#define D1X_KCONFIG_UI_UDLR_LINE_320()	/* [ 1] */	27,  4,  0,  2
#define D1X_KCONFIG_UI_UDLR_LINE_321()	/* [ 2] */	28,  5,  1,  3
#define D1X_KCONFIG_UI_UDLR_LINE_322()	/* [ 3] */	 0,  6,  2,  4
#define D1X_KCONFIG_UI_UDLR_LINE_323()	/* [ 4] */	 1,  7,  3,  5
#define D1X_KCONFIG_UI_UDLR_LINE_324()	/* [ 5] */	 2,  8,  4,  6
#define D1X_KCONFIG_UI_UDLR_LINE_325()	/* [ 6] */	 3,  9,  5,  7
#define D1X_KCONFIG_UI_UDLR_LINE_326()	/* [ 7] */	 4, 10,  6,  8
#define D1X_KCONFIG_UI_UDLR_LINE_327()	/* [ 8] */	 5, 11,  7,  9
#define D1X_KCONFIG_UI_UDLR_LINE_328()	/* [ 9] */	 6, 12,  8, 10
#define D1X_KCONFIG_UI_UDLR_LINE_329()	/* [10] */	 7, 13,  9, 11
#define D1X_KCONFIG_UI_UDLR_LINE_330()	/* [11] */	 8, 14, 10, 12
#define D1X_KCONFIG_UI_UDLR_LINE_331()	/* [12] */	 9, 15, 11, 13
#define D1X_KCONFIG_UI_UDLR_LINE_332()	/* [13] */	10, 16, 12, 14
#define D1X_KCONFIG_UI_UDLR_LINE_333()	/* [14] */	11, 17, 13, 15
#define D1X_KCONFIG_UI_UDLR_LINE_334()	/* [15] */	12, 18, 14, 16
#define D1X_KCONFIG_UI_UDLR_LINE_335()	/* [16] */	13, 19, 15, 17
#define D1X_KCONFIG_UI_UDLR_LINE_336()	/* [17] */	14, 20, 16, 18
#define D1X_KCONFIG_UI_UDLR_LINE_337()	/* [18] */	15, 21, 17, 19
#define D1X_KCONFIG_UI_UDLR_LINE_338()	/* [19] */	16, 22, 18, 20
#define D1X_KCONFIG_UI_UDLR_LINE_339()	/* [20] */	17, 23, 19, 21
#define D1X_KCONFIG_UI_UDLR_LINE_340()	/* [21] */	18, 24, 20, 22
#define D1X_KCONFIG_UI_UDLR_LINE_341()	/* [22] */	19, 25, 21, 23
#define D1X_KCONFIG_UI_UDLR_LINE_342()	/* [23] */	20, 26, 22, 24
#define D1X_KCONFIG_UI_UDLR_LINE_343()	/* [24] */	21, 27, 23, 25
#define D1X_KCONFIG_UI_UDLR_LINE_344()	/* [25] */	22, 28, 24, 26
#define D1X_KCONFIG_UI_UDLR_LINE_345()	/* [26] */	23, 29, 25, 27
#define D1X_KCONFIG_UI_UDLR_LINE_346()	/* [27] */	24,  1, 26, 28
#define D1X_KCONFIG_UI_UDLR_LINE_347()	/* [28] */	25,  2, 27, 29
#define D1X_KCONFIG_UI_UDLR_LINE_348()	/* [29] */	26,  0, 28,  0

/* kc_rebirth - enum blank */

#define DXX_KCONFIG_UI_LABEL_kc_rebirth	\
	/* [ 0] */	DXX_WEAPON_STRING_LASER "\0"	\
	/* [ 3] */	DXX_WEAPON_STRING_VULCAN "\0"	\
	/* [ 6] */	DXX_WEAPON_STRING_SPREADFIRE "\0"	\
	/* [ 9] */	DXX_WEAPON_STRING_PLASMA "\0"	\
	/* [12] */	DXX_WEAPON_STRING_FUSION "\0"	\
	/* [15] */	DXX_WEAPON_STRING_CONCUSSION "\0"	\
	/* [18] */	DXX_WEAPON_STRING_HOMING "\0"	\
	/* [21] */	DXX_WEAPON_STRING_PROXIMITY "\0"	\
	/* [24] */	DXX_WEAPON_STRING_SMART "\0"	\
	/* [27] */	DXX_WEAPON_STRING_MEGA "\0"

}