/*
 * This file is part of the DXX-Rebirth project <https://www.dxx-rebirth.com/>.
 * Vulkan renderer - SPIR-V shader bytecode.
 *
 * This file includes the generated SPIR-V headers produced by
 * glslangValidator during the build process.  Each header defines
 * a uint32_t array (the SPIR-V bytecode) and a size variable.
 */

#include "dxxsconf.h"
#if DXX_USE_VULKAN

#include <cstdint>

// These are generated by the build system from the GLSL sources.
// The headers use 'extern const' for external linkage.
#include "basic_vert_spv.h"
#include "basic_frag_spv.h"
#include "textured_vert_spv.h"
#include "textured_frag_spv.h"

#endif  // DXX_USE_VULKAN
